### ISSUE TITLE
Unexpected unread count 0

### ISSUE THREAD

**Issue by bibibilu** [GetStream/stream-chat-android#1223]
I am using latest 4.5.0.
This is an old issue occurred from time to time for all versions. Also the unread count will not reset when unread count 0 unexpectedly shows.

https://user-images.githubusercontent.com/55115952/104789654-8a096500-574a-11eb-9de3-c666c9ef0e9f.mp4

**Comment by tschellenbach** [comment]
What code are you using to fetch the unread count?

**Comment by bibibilu** [comment]
I am using livedata as follow:
```
val count = ChatClient.instance().getCurrentUser()?.totalUnreadCount ?: 0
badge.isVisible = count > 0
badge.number = count

ChatDomain.instance().totalUnreadCount.observe(viewLifecycleOwner, Observer {
  badge.isVisible = it > 0
  badge.number = it      
})
```

**Comment by JcMinarro** [comment]
Hello @bibibilu 
You shouldn't need to request the current user to obtain the total unread count.
Using `ChatDomain::totalUnreadCount` LiveData should be enough, because LiveData propagate all values from the time you subscribe to it.

I assume you are receiving new messages while you have the app opened, right?
Could you share with us the logcat of the events that you receive?

Why the badge is visible when it show the value `0`? Shouldn't it be hidden?
