### ISSUE TITLE
BaseChannelViewHolderFactory NOT FOUND

### ISSUE THREAD

**Issue by bibibilu** [GetStream/stream-chat-android#1536]
I was trying to set a customized ChannelViewHolder. I noticed this in ChannelListView in the new UI Component Artifact. However I just cannot find a BaseChannelViewHolderFactory, and the internal class ChannelViewHolder cannot be accessed. Do you have any idea how can I customized the ChannelListItem view? Thanks.
```
/**
     * Allows clients to set a custom implementation of [BaseChannelViewHolderFactory]
     *
     * @param factory the custom factory to be used when generating item view holders
     */
    public fun setViewHolderFactory(factory: ChannelListItemViewHolderFactory) {
        simpleChannelListView.setViewHolderFactory(factory)
    }
```

**Comment by rupinderjeet** [comment]
I suppose you are using new `ui-components` library, correct documentation is in Wiki > Ui Components > Cookbook. Here's the documentation for [Creating Custom View Holder Factory](https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#creating-custom-view-model-factory).

p.s.
@GetStream In this cookbook, sub-article title should be "Creating Custom View Holder Factory" instead of "Creating Custom View Model Factory"

**Comment by adasiewiczr** [comment]
Hey @bibibilu thanks for reporting this issue and @rupinderjeet thanks for the quick response!
In the new UI components artifact, you need to override `ChannelListItemViewHolderFactory ` instead of `BaseChannelViewHolderFactory `. 
As @rupinderjeet  mentioned - you can find an example in our [Cookbook](https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#creating-custom-view-holder-factory).
KDoc was fixed in PR mentioned above, Cookbook sub-article titles are also updated.
Let me know if you have any further questions.

**Comment by JcMinarro** [comment]
Hello @bibibilu @rupinderjeet 
It has been fixed and it is ready on the [last release](https://github.com/GetStream/stream-chat-android/releases/latest)
Could you check it?
