### ISSUE TITLE
.git error when loading the project

### ISSUE THREAD

**Issue by swordzman** [GetStream/stream-chat-android#1745]
**Describe the bug**
project loading doesn't finish and initialize

**SDK version**
30

**To Reproduce**
simply loading the project

**Expected behavior**
for the project to load and initialize and see the app folder and more

**Device:**
my pc
android studio 4.1.3

**Screenshots**
![Screenshot -1](https://user-images.githubusercontent.com/55040462/115112707-c8ced700-9f54-11eb-97b0-7d9943d706b7.png)
![Screenshot -2](https://user-images.githubusercontent.com/55040462/115112709-cbc9c780-9f54-11eb-83d5-191f50bb61f4.png)

**Comment by zsmb13** [comment]
Hi @swordzman!

Could you please grab the project from the `develop` branch, and see if you can run it there? https://github.com/GetStream/stream-chat-android/tree/develop

**Comment by swordzman** [comment]
Yes I tried that as well and had the same errors

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by swordzman** [comment]
Im not sure if its my pc or version or what this is doing truthfully, I am rwasonably new to codin and started learning with kotlin. I have another app I'm building and don't get this error. So confused lol

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by zsmb13** [comment]
Can you share the exact error you get on the `develop` branch? One way to make sure you're opening the project correctly is to browse for the `settings.gradle` file with Android Studio.

**Comment by swordzman** [comment]
sorry for the delay, I restarted my computer, re-downloaded the Deve file and these are 7 pictures of the errors I am getting.
It seems to have something to do with .git file that I am not sure how to handle.

Attached are the 7 pictures



________________________________

**Comment by swordzman** [comment]
yes, I opened the file as you requested
________________________________

**Comment by zsmb13** [comment]
Could you please provide the errors you get when opening the project on the `develop` branch?

Note that you didn't attach any pictures in your previous comment that said "attached are 7 pictures". Probably a problem with not using GitHub directly.

**Comment by swordzman** [comment]
I didn't know the pics didn't come through, here they are:
![New Screenshot -1](https://user-images.githubusercontent.com/55040462/115166383-e26d3d00-a080-11eb-83cb-b2ee2239d9db.png)
![New Screenshot -2](https://user-images.githubusercontent.com/55040462/115166384-e305d380-a080-11eb-8b3e-d95e886a5c5a.png)
![New Screenshot -3](https://user-images.githubusercontent.com/55040462/115166385-e305d380-a080-11eb-8771-48f6717e5271.png)
![New Screenshot -4](https://user-images.githubusercontent.com/55040462/115166386-e305d380-a080-11eb-9450-1d5283382782.png)
![New Screenshot -5](https://user-images.githubusercontent.com/55040462/115166387-e39e6a00-a080-11eb-948e-57ddadc92727.png)
![New Screenshot -6](https://user-images.githubusercontent.com/55040462/115166389-e39e6a00-a080-11eb-821b-2b13aff1ae13.png)
![New Screenshot -7](https://user-images.githubusercontent.com/55040462/115166390-e39e6a00-a080-11eb-9690-4606e8389972.png)

**Comment by swordzman** [comment]
I can't open the project, it will open simply in the project mode but I don't get to see the app and can't run it to test it at all.

**Comment by swordzman** [comment]
This seems to be the error repeatedly = can't generate a git version, this is not a git project. git status errors with error code: 128

It's like it can't read the .git file or something and thus can't load properly, done this with both developer and the ui code

**Comment by swordzman** [comment]
This is the full error log = 

2021-04-18
8:23 PM	Android Studio and plugin updates available
				Component: Android SDK Platform-Tools
				Update...

8:23 PM	Gradle sync started

8:24 PM	* daemon not running; starting now at tcp:5037

8:24 PM	* daemon started successfully

8:26 PM	Gradle sync failed: Error 128 executing `git rev-parse --show-toplevel`
				fatal: not a git repository (or any of the parent directories): .git
				Consult IDE log for more details (Help | Show Log) (2 m 40 s 665 ms)

**Comment by swordzman** [comment]
I searched up and maybe the plugin = 

"https://plugins.gradle.org/m2/"

is not available, would you know of a fix or a different plugin to use?
However, I am still not sure this is the problem???

**Comment by rupinderjeet** [comment]
Hello @swordzman 

> fatal: not a git repository (or any of the parent directories)

This suggests that you downloaded a zip of the code from repository. Downloaded projects do not have a git initialization. This issue is pretty common. If you cloned the project instead, you would not have faced the issue.

There are two fixes, and they both require that you have "Git" installed on your system. To check if you have it installed, just type "git" in a terminal and hit enter.

To fix it by initializing it yourself, open a terminal in the project directory, and run 

```
git init
```
And, after this, reopen/sync the project. It will work.

Or, to fix it by cloning the project, copy the https clone url from the place you downloaded the project. And, run following command in a terminal. It will download the project to your selected directory in terminal.

```
git clone copied-clone-url-here
```
And, after this, reopen/sync the project. It will work.

**Comment by JcMinarro** [comment]
Hello @swordzman 
As @rupinderjeet details, it seems that you download a zip from Github instead of clone the repo itselft. 
By the log you showed, it seems you already have installed git into your machine.
The easy way to fix it should be cloning the project into your machine.
You will need to run the following command:
```
git clone git@github.com:GetStream/stream-chat-android.git
```

BTW, We have added an extra condition into our gradle process to doesn't run the GitVersioner plugin if the compilation is not done on a CI machine. This plugin is used to auto-generate unique version of the SDK and it should be only needed on CI.
#1747 should fix it for you

**Comment by swordzman** [comment]
Unfortunately, I got this error and not sure how to clone a the project, it's my first time trying lol, and I am not sure exactly where to put the code you mentioned before???


I got this error =

![Clone error](https://user-images.githubusercontent.com/55040462/115255321-24879480-a0fc-11eb-9164-aa77570ad343.png)

**Comment by JcMinarro** [comment]
Ok, I can see you are using the Github GUI for that. What I was asking you before is using the terminal.
For some reason, Github GUI doesn't allow you to download the Github repository if you are not logged in.

BTW, We already does some changes to the Gradle Process to skip GitVersioners, so you shouldn't have the issue anymore.
Could you try to download the last version of our `develop` branch (https://github.com/GetStream/stream-chat-android/archive/refs/heads/develop.zip)?
