### ISSUE TITLE
Socket Exception

### ISSUE THREAD

**Issue by JayeshMohan4** [GetStream/stream-chat-android#2217]
**Describe the bug**
We are getting this error while going the app to background. Because of this we are not able to get push notification. Can you suggest a solution for this?

E/Chat:Events: onFailure ChatNetworkError http status -1, stream error code 1002: Server closed connection

**SDK version**
- 4.15.1

**To Reproduce**
1. Open the app
2. minimize the app for being in background
3. Send a message 
4. Push notificatio not getting on app while on background

**Expected behavior**
Need to push notification when app is on background

**Comment by adasiewiczr** [comment]
Hey @JayeshMohan4,
This is not a real issue, just information that the socket is disconnected but it'll be reconnected when the app goes back to the foreground.
This is expected behavior - push notifications are only received when a socket is disconnected. Check our docs [here](https://getstream.io/chat/docs/sdk/android/client/guides/push-notifications/) for further information.

**Comment by JayeshMohan4** [comment]
I am not receiving notification when it displays this error mentioned below that comes when i goes to background

E/Chat:Events: onFailure ChatNetworkError http status -1, stream error code 1002: Server closed connection

**Comment by JayeshMohan4** [comment]
#### Step 6
Setup the following push notification data payload at Stream Dashboard:
```json
{
"message_id": "{{ message.id }}",
"channel_id": "{{ channel.id }}",
"channel_type": "{{ channel.type }}"
}
```

Can you please explain about this set to do?

**Comment by samiuelson** [comment]
This is the push notification's data payload. It has to be configured at Stream Dashboard, in the `Chat > Push Notifications > Firebase > Data Template` section. The `Template` should remain set to `null`.

**Comment by bychkovdmitry** [comment]
Hello @JayeshMohan4 
Regarding the issue with push notifications, please check that the user who is sending the message is not muted. Apart from that, we found an issue with push notifications which might be caused by the network connection loss when the app is in the background. We are working on the fix and we will let you know once the fix is ready. Thanks again for submitting the issue.

**Comment by bychkovdmitry** [comment]
@JayeshMohan4 In the meantime, could you help us to debug the issue. How often (always / sometimes / never) do you experience problems with notifications when:
a. The app was brought to the background and the network connection remains stable  
b. The app was brought to the background, then the connection was lost (for example in airplane mode), then the connection was established again

**Comment by JcMinarro** [comment]
Hello @JayeshMohan4 
We have released a new version that should fix your issue.
Could you check [last version](https://github.com/GetStream/stream-chat-android/releases/latest)?
