### ISSUE TITLE
Direct Message - Same user can be added again and again for a DM,

### ISSUE THREAD

**Issue by anjuarevero** [GetStream/stream-chat-android#2341]
**Describe the bug**
Direct Message - Same user can be added again and again for a DM,
while taking the user for the next time , redirect to the chat window b/w the users .
It added new chat channel again and again

**SDK version**
- x.x.x

**To Reproduce**

**Expected behavior**

**Device:**
 - Vendor and model: [e.g. Samsung S8]
 - Android version: [e.g. 9]

**Screenshots**

**Comment by adasiewiczr** [comment]
Hey @anjuarevero,
can you provide a video with the steps to reproduce this issue?

**Comment by adasiewiczr** [comment]
hey,
are you creating those DM channels based on members instead of id? [Here](https://getstream.io/chat/docs/android/creating_channels/?language=kotlin#2.-creating-a-channel-for-a-list-of-members) you can find the docs explaining what's the difference between them.
Can you share the code you are using for creating the channel?

**Comment by adasiewiczr** [comment]
hey @anjuarevero,
do you still see this issue after creating a channel based on members?
