### ISSUE TITLE
Channel name changed to 'Channel without name'

### ISSUE THREAD

**Issue by bibinkrishnan** [GetStream/stream-chat-android#2350]
Channel name changed to 'Channel without name' when the user on the other end leaves from the channel and his avatar on message heading is showing as empty. Can we avoid changing the name to  'Channel without name' and also avatar on message head goes empty?

**SDK version**
-4.17.3
![screenshot-2021-09-15_07 35 59 296](https://user-images.githubusercontent.com/17172496/133427003-d8253a47-efd1-46fd-9566-c2a21aa5ff48.png)

**Comment by adasiewiczr** [comment]
Hey @bibinkrishnan,
this is expected behavior. Empty avatar and `Channel without name` are the default values used when the channel doesn't explicitly have `name` or `image` and there are no other members.
You can explicitly set the channel name and image during creation or update the existing channel and set `name` and `image`.
You can also override `stream_ui_message_list_header_untitled_channel` and `stream_ui_channel_list_untitled_channel` strings to set different default text.
