### ISSUE TITLE
Unread counts do not work while offline, nor do they sync after

### ISSUE THREAD

**Issue by jonschmidt** [GetStream/stream-chat-android#2484]
**Describe the bug**
Unread counts do not work while offline, nor do they sync after

**SDK version**
- io.getstream:stream-chat-android-offline:4.19.0

**To Reproduce**
1. Make sure you have an unread message in a channel
2. Go offline (airplane mode or whatever)
3. Mark the channel as read `chatDomain.markRead(cID)`
4. **Notice that the overall unread count is still 1**
5. Go back online
6. Mark the channel as read again
7. **Notice that the unread count is still 1** you will see something like this in the logs:
> Chat:ChatDomain ChannelController: Last message date [Thu Oct 14 19:49:55 GMT+02:00 2021] is not after last read event [Thu Oct 14 19:49:55 GMT+02:00 2021]; no need to update.

**Expected behavior**
The unread count is 0 when you read something offline, or at least, you can properly mark it read when you go back online

**Device:**
 - Vendor and model: Pixel 3
 - Android version: 29

**Comment by adasiewiczr** [comment]
hey @jonschmidt,
thanks for reporting. We'll investigate that

**Comment by jonschmidt** [comment]
No problem. Let me know if you need any more information

**Comment by adasiewiczr** [comment]
hey @jonschmidt,
some time ago we've released a new major version with a bunch of improvements in our internal logic.
You can find more in our [announcement blogpost](https://getstream.io/blog/android-v5-sdk-release/)  ([5.0.3](https://github.com/GetStream/stream-chat-android/releases/tag/v5.0.3) is the latest available version).
The issue mentioned above was fixed in #3162 which was a part of the v5 release.
