### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by bibinkrishnan** [GetStream/stream-chat-android#2777]
Hi,

I don't want the client to be connected throughout the app. I only want the client to be connected if I navigate to the chat screen. So I disconnect the user if he is not in the chat screen by 'client.disconnect()' method. . But after disconnection onMessageReceived() is getting called but unable to get sender name and message details on push notification. I tried 'disconnectsocket' it's working for me but my doubt is that after calling 'disconnectsocket' wheather it will connect the user to the chat app?. Is there any solution to get sender name and message details on push notification message?

**SDK version**
- 4.21.0

**Comment by leandroBorgesFerreira** [comment]
Hello @bibinkrishnan. Our Push notifications only receive channelId, messageId and channelType. We later perform an server call to request more information, after the call, the information will be availble. 

You can also override `NotificationHandler` and insert a custom logic, if you prefer: https://getstream.io/chat/docs/sdk/android/client/guides/push-notifications/#using-our-notificationhandlerfactory

**Comment by bibinkrishnan** [comment]
Can you share me the functioning of both 'client.disconnect()' and 'client.disconnectsocket()'?

Can I use client.disconnectsocket() to disconnect client without disconnecting push notification details?. What I need is to get push notification and its sender details after client discconection.

**Comment by leandroBorgesFerreira** [comment]
Hi @bibinkrishnan. 

`ChatClient.disconnect()` is equal to log out of the chat, just like you can logout from an account in Slack, Whatsapp, Telegram... This way a user won't receive any information more. No Pushes, no messages, no updates...

`ChatClient.disconnectsocket()` only disconnect from the socket. This way you interrupt the active connection with the chat backend. This is just like you close the app. You are still connected to your account, but not using it actively. In this situation, the user will start receiving push notifications, because the socket it no longer active. 

You question: **Can I use client.disconnectsocket() to disconnect client without disconnecting push notification details**
R: Yes, you can. That's exactly what `client.disconnectsocket()` does. Our SDK sends information in 2 ways. 1 - When the socket connection is active, it sends events through the socket, but if it is not active it 2 - Send push notifications. 

So, if you disconnect from the socket, you start receiving Pushes, as you want.

**Comment by leandroBorgesFerreira** [comment]
About the sender details, you won't receive this information in the payload of the notification, but you can use the information that you do get to retrieve the message and then get the sender. 

You can use `ChatClient.getMessage` and make a call to get the desired message. In the body of `Message` you can access `Message.user` to check the sender of the message. If you check how the SDK does it to have a code sample: https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/LoadNotificationDataWorker.kt#L103

**Comment by bibinkrishnan** [comment]
Thanks, This is very helpful. @leandroBorgesFerreira
