### ISSUE TITLE
Handle Attachment.upload when edit message (like MessageSendingService)

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#3065]
We Implement our own FileUploader to delegate upload logic to stream's implementation (update message's attachments lazily when upload is finished)
However, it seems only ChatDomain.sendMessage works as I expected! ([handle Attachment.upload](https://github.com/GetStream/stream-chat-android/blob/c086bbf10641816762aa24b11e760853202bff8d/stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/MessageSendingService.kt#L46))

I know that there is a way to solve this problem, however, it would be better if sdk support this.

This is my idea to implement editing message with attachments.
- use ChatClient.sendFile or sendImage to get url (to use FileUploader)
- build Attachment with url
- edit message with url-filled attachments

**Comment by filbabic** [comment]
Hey @workspace !

Sorry for the late reply on this ticket. I'm not sure that BE allows editing of messages to add attachments. That's because we usually upload them to our CDN and then the BE resolves the links, types and so on.

Could you provide a message where you manually add the attachments before sending? E.g. add the `Attachments` property to the message, with each item describing the link properties as we use them in the SDK, as well as the file/mime types?

**Comment by filbabic** [comment]
Closing since it's been some time!
