### ISSUE TITLE
Removed members can still post message

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#310]
When a member is successfully removed from a conversation while still in the message detail, that deleted member could still post message.

**Comment by tschellenbach** [comment]
there are 2 possible explanations for this:

1. your app has permissions disabled (check the dashboard)
2. you are using a channel type that allows non-members to post messages. for instance the livestream channel type allows this.

we have extensive test coverage at the API level that ensures that you need to be a member in order to post a message (for channels that have permissions configured like that).

**Comment by Chikrix** [comment]
So there's nowhere in my app where I'm currently setting any permissions or doing something to disable permissions. Also, I'm using a `messaging` channel type. Where would I look to check this?

**Comment by tschellenbach** [comment]
You can see the dashboard here: https://getstream.io/dashboard/

![image](https://user-images.githubusercontent.com/265409/69024463-102bef00-0980-11ea-97f5-e35a6e0612aa.png)

**Comment by Chikrix** [comment]
Got it. I was using the app which had permissions disabled. Thanks for this.

**Comment by tschellenbach** [comment]
No problem.
