### ISSUE TITLE
Add an option to Enable/Disable the command suggestion dialog

### ISSUE THREAD

**Issue by JeromeCHA** [GetStream/stream-chat-android#3370]
# Describe the feature you'd like to see in the SDK
## What we want
Since `giphy` is the only command we want, I think it should be nice to trigger the `giphy` command without displaying the command dialog.

| Now | What we want |
|---|---|
| <img width="414" alt="image" src="https://user-images.githubusercontent.com/11457628/164581844-aea57cf1-2e73-4e75-a792-4d7f74d04f1d.png"> | <img width="359" alt="image" src="https://user-images.githubusercontent.com/11457628/164581859-fceb5640-3ee5-413b-af56-140951dc9307.png"> |

## The problem

Since we only use `giphy` command, it has one unnecessary click. I think it has no real meaning to display this dialog for only one command.

## The solution

Do you think it is possible to and an option for the developers to bypass this dialog?

**Comment by filbabic** [comment]
Hey @JeromeCHA !

As with this: https://github.com/GetStream/stream-chat-android/issues/3371 I imagine we can cover it in one PR so that the behavior is uniform - you can customize the actions/commands and how they behave and a way to trigger them.

We'll look into how we can support this as it's not a common request. I can't provide a timeline just yet but we'll research it this sprint (next two weeks) and see what we can do.

Thanks! :]

**Comment by JeromeCHA** [comment]
Hi @filbabic 
Thank you! That would be great 🙏

**Comment by MarinTolic** [comment]
Hey @JeromeCHA ,

The PR for this feature request is ready and can be seen here: #3515
We have publicly exposed `MessageInputView.switchToCommandMode(command: Command)`.

Please note that there is a patch within the PR that implements your given use case. Feel free to use it and give us feedback. :smile: 

Also, I've left some comments within the patch file that explain why a particular approach was taken. :smile:
