### ISSUE TITLE
Hide options like thread reply, flag message on long click of message in Jetpack Compose UI is not possible

### ISSUE THREAD

**Issue by monil-shah-13** [GetStream/stream-chat-android#4177]
**Bug Description**
We are migrating from Android xml based sdk to the latest version of Jetpack Compose sdk for chat. In xml based ui, we were getting an option to disable message options like thread reply, flag message etc. But in the new Jetpack Compose based ui we do not have that option. 

We are using the **MessagesScreen** component in our app. It does not allows to remove some of the message actions that we do not want in our app. 

**SDK version**
- 5.9.0

**Expected behavior**
We would want a simple way to remove some of the message actions like flag message, thread reply from the options that we get on long press of the message

**Comment by filbabic** [comment]
Hey @monil-shah-13 !

If you check out our [compose documentation](https://getstream.io/chat/docs/sdk/android/compose/message-components/selected-message-menu/) you'll see that the options are customizable and you can remove them.

Speficially in the [usage part](https://getstream.io/chat/docs/sdk/android/compose/message-components/selected-message-menu/#usage), you can build your own set of message options and exclude all of these - such as reply, flagging, etc.

LMK if you're able to use this API an if so, if it resolves your issue! :]

**Comment by monil-shah-13** [comment]
Hey @filbabic,

Thanks for quick response.

The compose documentation says 
`This is a stateless component that you can easily add to your UI if you're building a custom Messages screen. `

We are using the **MessagesScreen** component inside the **ChatTheme**. 
It provides option to give custom reactions but does not support removing the message options.

**Comment by filbabic** [comment]
Hey @monil-shah-13 !

As described in another ticket - it's not only a stateless, but also a bound component that has its own ViewModel that sets up everything for you. Also - what you're doing is building a pretty custom Messages screen, so as per the docs we recommend using Bound components.

Additionally - for disabling options, is there a reason why you're not using `ownCapabilites` and channel capabilities/permissions v2, to disable all of these options? 

https://getstream.io/chat/docs/android/user_permissions/?language=kotlin&name=compose

You can read more about it here - basically, in your app Dashboard, you can disable permissions for different types of users and channels, so that your users can't e.g. reply to messages and similar.

**Comment by JayMehta97** [comment]
Hi @filbabic,

@monil-shah-13 and I work in the same team.

We have already upgraded to permissions V2 and also have migrated all of our users to new roles. We have a role in our app which has the following permissions for a specific channel type:
```
        "add-links",
        "create-reaction",
        "create-message",
        "delete-attachment-owner",
        "delete-message-owner",
        "delete-reaction-owner",
        "read-channel",
        "run-message-action-owner",
        "upload-attachment"
```

As you can see in the permissions above we haven't added any permission to allow flagging a message or replying to  a thread yet those options can be seen in UI. I have also check the permissions for this role for this type of channel from dashboard and there also it doesn't have such permissions.

This chat channel has users who have different roles, so few members have role A and few have role B and all are part of same chat. Users with role B do have the permission to flag a message but users with role A don't, yet users with role A can see flag message option in UI.

I am able to disable `threads and reply` option from dashboard but we would prefer to have a way to do it from code. Currently we have multiple apps with multiple channel types in them and I would have to go through each of them to do from dashboard whereas if it is from code then I can run it with other chat update script.

**Comment by filbabic** [comment]
Hey @JayMehta97 !

That's weird - the capabilities should be properly reflected. As per the way to manually disable stuff, that does seem like something that makes sense and we can add more support for.

However, if you use bound components (instead of screen), you can just build your own list of `MessageOptionItemState`s that represent the actions a user can make against each message, as outline in the [component documentation](https://getstream.io/chat/docs/sdk/android/compose/message-components/selected-message-menu/).

Let me know if this makes sense and you can use it, or if we need to expose extra functionality to set up this use case. Basically, you'd just need to build the default options and then filter out the actions you don't need, or simply build the only the options you want to support yourself.

**Comment by JayMehta97** [comment]
Hey @filbabic,

I found a way to disable `replies` feature for channel type via code from here - https://getstream.io/chat/docs/node/channel_features

Example code if anyone has a similar query:
```
await serverClient.updateChannelType(channelTypeName, {
  replies: false,
  grants: {
    ...
  }
})
```

Regarding flag message option, it would be even better if you could check why `channel own capabilities` has `flag-message` even though that user role doesn't have that permission so that we can manage it from role itself. If that is not possible then a function from SDK would be helpful, similar to `setMessageFlagEnabled` (in XML based SDK)

**Comment by filbabic** [comment]
Hey @JayMehta97 !

That makes sense - we'll investigate as to why this happens and in the meantime, I think you can work around it by filtering the options yourself, using the bound components.

I'll keep you up to date!

**Comment by JayMehta97** [comment]
Hey @filbabic,

From what I can see in MessageOptions.kt file, it looks there isn't a check for `flag-message` capability when preparing the flag message MessageOptionItemState.

This is the code block:
```
if (!isOwnMessage) {
    MessageOptionItemState(
        title = R.string.stream_compose_flag_message,
        iconPainter = painterResource(R.drawable.stream_compose_ic_flag),
        action = Flag(selectedMessage),
        titleColor = ChatTheme.colors.textHighEmphasis,
        iconColor = ChatTheme.colors.textLowEmphasis,
    )
} else null,
```

And the capabilities that are being read:
```
// user capabilities
val canQuoteMessage = ownCapabilities.contains(ChannelCapabilities.QUOTE_MESSAGE)
val canThreadReply = ownCapabilities.contains(ChannelCapabilities.SEND_REPLY)
val canPinMessage = ownCapabilities.contains(ChannelCapabilities.PIN_MESSAGE)
val canDeleteOwnMessage = ownCapabilities.contains(ChannelCapabilities.DELETE_OWN_MESSAGE)
val canDeleteAnyMessage = ownCapabilities.contains(ChannelCapabilities.DELETE_ANY_MESSAGE)
val canEditOwnMessage = ownCapabilities.contains(ChannelCapabilities.UPDATE_OWN_MESSAGE)
val canEditAnyMessage = ownCapabilities.contains(ChannelCapabilities.UPDATE_ANY_MESSAGE)
```

It seems the `canFlagMessage` capability is not read from `ownCapabilities` and not validated when showing option in UI.

**Comment by filbabic** [comment]
Hey @JayMehta97 !

We've chatted with the BE team about this - some of the options seem to be on the BE side, the logic might need some updates, as for the FE side, we'll look into improving the logic, but as mentioned, in the meantime, you should be able to filter out the options on your end as a workaround. Have you tried doing so?
