### ISSUE TITLE
No option to highlight a message in MessageScreen in Jetpack Compose

### ISSUE THREAD

**Issue by monil-shah-13** [GetStream/stream-chat-android#4180]
**Bug Description**
There was a way to pass the **messageId** while creating an instance of **MessageFragment** in the xml based ui sdk. But in the Jetpack Compose ui sdk, there is no such option while rendering **MessageScreen**.

We used this option to highlight the message that the user clicked in the notification to indicate the message which user want to see is the one that is highlighted.

In the XML ui sdk, it was very simple to use by just passing the messageId and that message would be highlighted for a few seconds. 

**SDK version**
- 5.9.0

**Expected behavior**
Would want a similar kind of way like xml based ui sdk to highlight a message in the **MessageScreen** component.

**Comment by filbabic** [comment]
Hey @monil-shah-13!

As described in another ticket, some of these can be resolved by using Bound components. This feature is something we've actually added in one of our PRs that's open, but it'll most likely be target for our next major release, which should be ready in a few weeks, since it also includes a ton of other improvements and polish.

In the meantime, you can use the ViewModel to focus a message with a given ID, after opening the screen and showing the UI you need. `MessageListViewModel.focusMessage(messageId)` or `MessageListViewModel.scrollToMessage(message)`.

**Comment by monil-shah-13** [comment]
Hi @filbabic,

As per your suggestion, have started using Bound Components and that allowed us with many lower level customisation. Along with the `MessageList` component, we were able to use `MessageListViewModel.focusMessage(messageId)` to focus a message with a given ID.

Thanks for helping out.

**Comment by filbabic** [comment]
Sounds awesome @monil-shah-13 !

Thank you so much for letting us know! :]
