### ISSUE TITLE
"invite" field not working properly for querying channels

### ISSUE THREAD

**Issue by muaviyaijaz123** [GetStream/stream-chat-android#4782]
**Describe the bug**
I get a channel list using the following filters to display only those channels in which a user is invited.

   ChannelListViewModelFactory(
            filter = Filters.and(
                FIlter.eq("type","messaging")
                Filters.eq("invite", "pending"),
                Filters.`in`("members", listOf(userId)),
            )
        )

On first time, it fetches the correct result ,  but once i accept the invite it doesn't fetch the correct result unless i launch the app gain. I'm assuming query field "invite" is not getting updated correctly on backend

**SDK version**
- 5.12.0

**To Reproduce**
- Run the app with mentioned above query 
- Channels showing as expected
- accept the request
- see the channels list again, it doesn't refresh

**Expected behavior**
I expect to get updated list once i accept the request

**Device:**
 - Vendor and model: Samsung A30
 - Android version: 11

**Screenshots**

- On first time app runs:
<img width="390" alt="Screenshot 2023-04-07 at 2 40 20 PM" src="https://user-images.githubusercontent.com/90596703/230586388-b8889f7d-526e-44c0-b6fb-73eb76107cc4.png">
<img width="1027" alt="Screenshot 2023-04-07 at 2 41 31 PM" src="https://user-images.githubusercontent.com/90596703/230586409-c2f0c02e-281f-41a2-8e3f-f15ca4a3d253.png">

- After i accept invite:
<img width="394" alt="Screenshot 2023-04-07 at 2 45 01 PM" src="https://user-images.githubusercontent.com/90596703/230586953-7ff60497-6384-4419-bef7-4d57240fe601.png">
^ Channel content ha been updated to "... joined this chat" but this channel shouldn't be showing in the channels list now in the first place after update

**Comment by muaviyaijaz123** [comment]
@JcMinarro any update on this?

**Comment by JcMinarro** [comment]
Hello @muaviyaijaz123 

The `invite` field should properly be updated on backend, sadly, not all events can be handled locally with the default implementation. That is because we provide an option to inject a `ChatEventHandler` to react to concrete cases like your one. [Here](https://getstream.io/chat/docs/sdk/android/client/guides/channel-list-updates/#custom-chateventhandler) you can find the documentation about that.

**Comment by JcMinarro** [comment]
Hello @muaviyaijaz123 

You will need to implement your own `ChatEventHandler` and return a result on the case the invitation is accepted.
When the invitation is accepted, a new event should be received (on that case I think it should be `NotificationInviteAcceptedEvent` type), so, you will need to handle this case. The expected behaviour you want to achieve is that the `Channel` dissappear from the list, so for that you will need to return `EventHandlingResult.Remove(event.cid)`. On the rest of cases you want to follow the same logic, so you can reuse our implementation.
Let me share an implementation of a class you can use (You will need to test it and see if it cover all your cases):
```
class MyChatEventHandler(
    channels: StateFlow<Map<String, Channel>?>,
    clientState: ClientState,
    globalState: GlobalState
) : DefaultChatEventHandler(channels, clientState, globalState) {
    override fun handleChatEvent(
        event: ChatEvent,
        filter: FilterObject,
        cachedChannel: Channel?,
    ): EventHandlingResult = when (event) {
        is NotificationInviteAcceptedEvent -> EventHandlingResult.Remove(event.cid)
        else -> super.handleChatEvent(event, filter, cachedChannel)
    }
}
```

**Comment by muaviyaijaz123** [comment]
@JcMinarro Hi, Yeah as you mentioned , I did handle this event but chat reappears for some reason. Also if you message in any other channel in which you re already a member, it gets shown too in the list, though it shouldn't as the list should only show requests.

Can it be on accepting invite , many other events are being generated too?

**Comment by JcMinarro** [comment]
@muaviyaijaz123 

If a channel reappears, it is because a new event arrives to the device and `EventHandlingResult.Add()`  is returned.
In your case, as far as I understand, only new invitation to channels should be shown, right?
On that case I think you only need to handle 2 events `NotificationInviteAcceptedEvent` that should return `EventHandlingResult.Remove(event.cid)` and `NotificationInvitedEvent` that should return `EventHandlingResult.WatchAndAdd(event.channel)`. The rest of event should be Skip.
The class should be something like the following class (I added a log that you can check to know which events are received and verify it is working fine to you): 

```
object MyChatEventHandler : ChatEventHandler {
    override fun handleChatEvent(
        event: ChatEvent,
        filter: FilterObject,
        cachedChannel: Channel?,
    ): EventHandlingResult = when (event) {
        is NotificationInviteAcceptedEvent -> EventHandlingResult.Remove(event.cid)
        is NotificationInvitedEvent -> EventHandlingResult.WatchAndAdd(event.cid)
        else -> EventHandlingResult.Skip
    }.also {
        println("Received event: '$event' and the result returned is: '$it'")
    }
}
```

**Comment by muaviyaijaz123** [comment]
@JcMinarro Yes working fine now. Seems like i was missing the Skip Event :( . Thanks for the help!!
