### ISSUE TITLE
Sender does not always receive new message event when sending a PDF

### ISSUE THREAD

**Issue by zeroarst** [GetStream/stream-chat-android#5269]
**Describe the bug**
When sending a pdf, the sender does not always receive a new message event. Sending other message types such as text, image or giphy are fine. 

This is the pdf file we tested. It is downloaded from the internet.
[example.pdf](https://github.com/GetStream/stream-chat-android/files/15450854/example.pdf)

**SDK version**
- 6.1.0, 6.4.0

**To Reproduce**

Please see the attached video. 

I tested with two emulators. The `LogCat` on the right shows logs of the right emulator.

When sending a PDF from the left emulator, the recipient on the right emulator always received a new message event (`type=message.new`).

However, when sending a PDF from right emulator, the sender on the right emulator did not always received a new message event (`type=message.new`). Sometimes it did, which seemed very random.

Essentially, what we want to do is track any new message sent by the sender. Therefore, we think subscribing to the new message event should be a good approach. We just need to filter out whether the user ID in the message data is the same as the current connected user's ID.

That said, we are not sure if there is a better way to achieve this. If there is, please advise how.

**Expected behavior**
Always receive a new message event when sending a PDF as other message types.

**Device:**
 - Vendor and model: [e.g. Samsung S8]
 - Android version: [e.g. 9]

**Screenshots**

https://github.com/GetStream/stream-chat-android/assets/1834837/cd955f5c-874c-4f24-8cf5-6629c06c87f5

**Comment by JcMinarro** [comment]
Hello @zeroarst 
Sorry for the delay.

Watching your video, it looks like your `MainViewModel` is the one that is not receiving this event, because the list of messages is updated properly with the double-check that notifies the receiver already read the message.
I think it could be happen because when you are looking for the pdf file, a new activity is started over the app, and, by some reason, your viewModel is stopping to listen for new events.

Regarding your use case, you should be able to inject a custom plugin to the SDK and override the method that is called after a new message is sent (obtaining a result object that notifies you if the message was sent properly or was any error).
Reviewing our `Plugin` interface, I can see there are some abstract methods annotated with `@InternalStreamChatApi` that will complicate the implementation you need to do. So I am working on a PR to simplify the implementation of our `Plugin` interface (#5320)

After it is merged, you should be able to do something like:
```
// Create a custom plugin factory that provide you implementation
val myCustomPluginFactory = object : PluginFactory {
    override fun get(user: User): Plugin = object : Plugin {
        override fun onUserSet(user: User) { }
        override fun onUserDisconnected() { }
        override suspend fun onMessageSendResult(
            result: Result<Message>,
            channelType: String,
            channelId: String,
            message: Message,
        ) {
            println("The user was sending the message: $message to the channel CID '$channelType:$channelId'")
            result
                .onError { println("The message wasn't sent because the error $it") }
                .onSuccess { println("The message was properly sent, it is the full message that backend stored $it") }
        }
    }
}

val client = ChatClient.Builder(apiKey, context)
    [...]
// Inject your implementation to the ChatClient instance
    .withPlugins(offlinePlugin, statePluginFactory, myCustomPluginFactory)
    .build()
```
