### ISSUE TITLE
How to implement account login?

### ISSUE THREAD

**Issue by Niksha36** [GetStream/stream-chat-android#5390]
**Describe the bug**
Now i know that the ChatClient can not survive a process death and i successfully implemented app sign up saving User data class in onDestroy. What if i want implement not only some kinda registration but sign in and do not change every time user name ? I see only one option - save User data class in firestore and when user enteres a phone number check is there user with this phone and retrive it and provide to ```connectUser``` function. Is it only one way to add this behavior, is it correct approach?
**SDK version**
- 34

**Comment by aleksandar-apostolov** [comment]
Hey @Niksha36 

The best way to seek guidance is by opening a discussion, as this isn’t a feature request or a bug.
If you still believe it’s a bug, please provide steps to reproduce it. For feature requests, feel free to submit them directly.

To answer your question, the SDK does not store user data by design. The user must be supplied each time the SDK is initialised, and you can store this data offline as needed. The reason for this is because the user is managed by you and your app/backend. Storing it in firebase is one way to achieve this.

Thanks,
Alex

**Comment by Niksha36** [comment]
> Hey @Niksha36
> 
> The best way to seek guidance is by opening a discussion, as this isn’t a feature request or a bug. If you still believe it’s a bug, please provide steps to reproduce it. For feature requests, feel free to submit them directly.
> 
> To answer your question, the SDK does not store user data by design. The user must be supplied each time the SDK is initialised, and you can store this data offline as needed. The reason for this is because the user is managed by you and your app/backend. Storing it in firebase is one way to achieve this.
> 
> Thanks, Alex

Thanks Aleksandar! I am sorry you are right
