### ISSUE TITLE
A way to skip push notifications for certain events

### ISSUE THREAD

**Issue by skgwazap** [GetStream/stream-chat-android#555]
The use case:
We have some special "system" messages in our chats (we have a special admin user for that). For those messages we have special layout and logic and we don't want users to receive push notifications for those messages.
The problem:
Users receive push notifications for these "system" messages.
Is there a way to achieve this? I've tried to use "silent": true, but without success.

I know, that this android repo is not the right place to ask this kind of questions (backend related), but, anyway, it affects our android users too.

**Comment by samiuelson** [comment]
What you can do is to turn off automatic notification displaying when Firebase cloud message arrives. To do this you'll need to send "data message" instead of "notification message" (https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages). You'll need to register `FirebaseMessagingService` instance in manifest, parse new message in `onMessageReceived()` function and decide whether to show a notification or not. 

To enable "data message" set up a data template in the dashboard. Here's more info on what data is available for cloud messages https://getstream.io/chat/docs/push_template/.

**Comment by tschellenbach** [comment]
@tbarbugli ^^

**Comment by skgwazap** [comment]
Thanks.
Yeah, that could be an option for Android but I doubt that this will work for iOS. I wonder if there is a general solution to control push notifications on GetStream site.

**Comment by JcMinarro** [comment]
Hello @skgwazap 
Some weeks ago we released a feature that cover this case.
You can see the documentation here:
https://getstream.io/chat/docs/silent_messages/?language=kotlin&q=silent

An extra attribute has been added to the Message entity:
https://github.com/GetStream/stream-chat-android-client/blame/master/library/src/main/java/io/getstream/chat/android/client/models/Message.kt#L79

**Comment by skgwazap** [comment]
I tried to use `silent = true` but it seems like it's a client side setting and it doesn't prevent the service from sending push notifications.
Anyway, we decided to switch to our own webhook-based implementation for sending push notifications.
