### ISSUE TITLE
Message extraData is allways recieved empty.

### ISSUE THREAD

**Issue by Hersy** [GetStream/stream-chat-android#612]
In order to give a message special functionalities, I have been sending messages with extraData via backend, but none of it comes through when recieved on the android app, EVEN THOUGH, I can see my extraData in the getStream http logger.
Is it nullified or emptied in any of the android classes?

**Comment by tschellenbach** [comment]
sounds like a JSON encoding/decoding issue. what do you think @JcMinarro ?

PS what app are you working on?

**Comment by tschellenbach** [comment]
Perhaps related to this: https://github.com/GetStream/stream-chat-android/issues/599

**Comment by Hersy** [comment]
Please, just remove the "@IgnoreDeserialization" line from the model classes Message.kt, Attachment.kt, Reaction.kt, Channel.kt, and User.kt for the next update, that should solve the problem.
The current state is unacceptable... as it entirely removes the bak-to-front customization for the android chat interfaces.

**Comment by tschellenbach** [comment]
I agree, @JcMinarro will pick it up.

**Comment by JcMinarro** [comment]
Hello @Hersy 
Thanks for your feedback.
When we use `@IgnoreDeserialisation` and `@IgnoreSerialisation` it is because we provide some adapter that handles that process, it is not because we want to remove customization on our entities.
On that case, `Message`, `Attachment`, `Reaction`, `Channel` and `User` are `CustomObject`, and the CustomObject  serialize/deserialize process is handled into `CustomObjectGsonAdapter`

As Thierry said, this issue is duplicated and will be cover on #599 so I am going to close this issue

**Comment by Hersy** [comment]
Sorry for being too harsh... :c @JcMinarro
