### ISSUE TITLE
Regression bug: QueryUsers failed with error: "field "id" expects type string"

### ISSUE THREAD

**Issue by pixnbit** [GetStream/stream-chat-android#812]
In the new 4.4.0, our auto-complete search stopped working. The previous release worked fine.

We're getting errors of:

`Status code: 400, with stream code: 4, description: QueryUsers failed with error: "field "id" expects type string"`

```kotlin
        val autocomplete = FilterObject("name", FilterObject("\$autocomplete", newQuery))
        val sort = QuerySort().asc("last_active")
        val filter = and(
            autocomplete,
            eq("teams", contains(it)),
            nin("id", listOf(id, "bot")))
        val query = QueryUsersRequest(filter, 0, 30, sort, false)

        val result = ChatClient.instance().queryUsers(query).execute()
```

If I remove the `nin` condition, it will work. The purpose of it was to exclude self and some bot ids

**Comment by JcMinarro** [comment]
Hello @pixnbit 
We already added the [autocomplete filter](https://github.com/GetStream/stream-chat-android/blob/master/stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Filters.kt#L162)

Let us check the `nin` filter issue

**Comment by zsmb13** [comment]
I believe your issue is that `id` is `null` when you're creating these filters, hence the error message from the API saying that it's not a string. This is the only way I could get this call to fail on any version of our SDK.

If you don't always have an `id` to pass in there, you could use something like [`listOfNotNull`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/list-of-not-null.html), like so:

```kotlin
Filters.nin("id", listOfNotNull(id, "bot"))
```

Of course, if you expected the `id` to contain the current user's ID by the time you're making this call, double-check when and how you're getting that value.

**Comment by pixnbit** [comment]
Aha, it's my fault this time. So we've been querying with `id` from the `Fragment.getId()` returning an integer. It was supposed to be the current user's id instead, in `String`. Your previous Stream SDK was okay with it, but not the new one. Good that it caught a bug for me in more restrictive checks.

**Comment by pixnbit** [comment]
@JcMinarro thanks I'll be using the new autocomplete filter (I think I filed a request ticket for it a while back)
