### ISSUE TITLE
ChannelsView no show with "wrap_content" layout height

### ISSUE THREAD

**Issue by bibibilu** [GetStream/stream-chat-android#814]
I am trying to divide channels to different types (group message/ direct messages), and using ChannelsView.setChannels().
But the ChannelsView only show when layout height is assigned a specific size. It does not show with "wrap_content" height. I am using SDK 4.4.1.

**Comment by zsmb13** [comment]
`ChannelsView` uses a `RecyclerView` called `ChannelListView` internally, and it's generally meant to have a fixed height and be scrollable within that. If you want to directly manipulate this contained `RecyclerView`, for example for nested scrolling and similar solutions, using `ChannelListView` directly might be the way to go for you.

`ChannelsView` is just a wrapper around `ChannelListView`, adding loading and empty state views to it. Note that you'll have to handle these yourself if you choose to use `ChannelListView`.

**Comment by bibibilu** [comment]
Hi! I tried wrap_content with ChannelListView and channels are not showing as well. Here is my layout structure, any suggestion?
![image](https://user-images.githubusercontent.com/55115952/98607798-bb733980-229e-11eb-9148-f105ece34a61.png)

**Comment by zsmb13** [comment]
Hi @bibibilu, this layout code itself seems correct (by the way, if you can include the actual code instead of the screenshot next time, that'd be more helpful).

The reason why `ChannelListView` would not be visible at this point is that we use [`RecyclerView#setHasFixedSize`](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView#setHasFixedSize(boolean)) to optimize performance for the usual case, where the `RecyclerView` has a fixed height that never changes.

For your use case, you'll have to disable this, by making a call like this after inflating your view:

```kotlin
groupChannelsView.setHasFixedSize(false)
```

This should let the view resize as you add items to its adapter.

**Comment by bibibilu** [comment]
It works. Thanks so much! @zsmb13
